owner: linkspreed
repo: status
user-agent: linkspreed

sites:
  - name: LINKSPREED Website
    url: https://linkspreed.com
  - name: UIID
    url: https://uiid.linkspreed.com

assignees:
  - linkspreed

status-website:
  name: LINKSPREED Status
  baseUrl: /status        # weglassen, wenn du cname nutzt
  # cname: status.linkspreed.com
  theme: dark

secrets: []
